# -*- coding: utf-8 -*-
"""Inventario de productos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13N8qKhVgu4I27FmOlQCzzHzbqDAdiKqb
"""

#Inventario

inventario = {}

def agregar_producto():
  print("Estos son los productos que anteriormente ingreso:")
  for clave,valor in inventario.items():
    print(clave,valor)
  print("Ingrese el codigo para identificar el producto:")
  ide = input()
  if inventario.get(ide+"-nombre"):
    print("Lo sentimos, ya existe un producto con ese numero")
  else:
   inventario[ide+"-nombre"] = input("Ingrese su nombre: ")
   inventario[ide+"-cantidad"] = input("Ingrese su cantidad: ")
   inventario[ide+"-precio"] = input("Ingrese su precio: ")

def eliminar_producto():
  print("Ingrese el codigo del producto que desea eliminar:")
  for clave,valor in inventario.items():
    print(clave,valor)
  ide = input()
  if inventario.get(ide+"-nombre"):
    del(inventario[ide+"-nombre"])
    del(inventario[ide+"-cantidad"])
    del(inventario[ide+"-precio"])
  else:
    print("Lo sentimos, pero no se encuentra.")

def buscar_producto():
  print("Ingrese el numero del producto que desea buscar")
  ide = input()
  if inventario.get(ide+"-nombre"):
   print(inventario[ide+"-nombre"])
   print(inventario[ide+"-cantidad"])
   print(inventario[ide+"-precio"])
  else:
   print("Lo sentimos, no se encontro el producto")

def listar_inventario():
  for clave,valor in inventario.items():
    print(clave,valor)

def guardar_inventario():

  with open("inventario.csv",mode="a",newline ='') as inventario_csv:
    for i in inventario.values():
      inventario_csv.write(i+"\n")
#MAIN
print("""Bienvenido, seleccione una de las opciones:
       1. Agregar un producto.
       2. Eliminar un producto.
       3. Buscar un producto.
       4. Listar un producto.
       5. Guardar el inventario.
       6. Cargar el inventario.""")
try:
 decision = int(input())
except:
  print("Seleccione una opcion valida.")
while decision != 6:
 if decision == 1:
  agregar_producto()

 elif decision == 2:
  eliminar_producto()

 elif decision == 3:
  buscar_producto()

 elif decision == 4:
  listar_inventario()

 elif decision == 5:
  guardar_inventario()

 #Main dentro del ciclo
 print("""Bienvenido, seleccione una de las opciones:
       1. Agregar un producto.
       2. Eliminar un producto.
       3. Buscar un producto.
       4. Listar un producto.
       5. Guardar el inventario.
       6. Cargar el inventario (Salir del codigo).""")
 decision = int(input())

def cargar_archivo():
  with open("inventario.csv",mode="r") as inventario_csv:
    leer_csv = inventario_csv.read()
    print(leer_csv)

cargar_archivo()